name: 'Publish'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    name: 'Tests'
    uses: ./.github/workflows/modules/__call__checks.yaml

  build:
    name: 'Build'
    needs: [tests]
    uses: ./.github/workflows/modules/__call__build.yaml

  publish:
    name: 'Publish'
    needs: [build]
    uses: ./.github/workflows/modules/__call__publish.yaml
